### ISSUE TITLE
Filter by Active Status

### ISSUE THREAD

**Issue by SenorSmartyPants** [johman10/flood-for-transmission#130]
I would like to be able to see all active torrents, ones either uploading or downloading, or checking. Basically the view available in Transmission remote on android.

**Comment by johman10** [comment]
I can add a filter for this, it would be pretty straightforward.

I have some other features to look at left but this can be the next thing on my list. :)

**Comment by johman10** [comment]
The other issues were quicker than I expected to here I am letting you know that I just shipped a new version with an active filter included.

Hope you like it! :)

**Comment by SenorSmartyPants** [comment]
LSIO docker finally updated and included this change.

The Active view is displaying all torrents that I have seeding regardless of if they are actually uploading. That's not what I would like to see.

- torrent is using upload
- torrent is using download
- torrent is verifing files

**Comment by johman10** [comment]
@SenorSmartyPants thanks for getting back to me.

I guess I misunderstood. Right now actiave is basically all items that show a play icon in the progress bar. I can reopen this and optimize the filter a little, but chances are that this will result in fairly weird behaviour because it keeps switching, one moment it's actively uploading/downloading, the other it's not so the filter will be very jumpy I'm afraid.

As long as you're aware of that I guess it shouldn't be a problem. ;)

**Comment by SenorSmartyPants** [comment]
That sounds like the behavior I'm looking for.

**Comment by SenorSmartyPants** [comment]
It takes so long for the docker images I use to pull your changes I have seen this latest fix yet. I'll pull again today.
