### ISSUE TITLE
Tree view in Files

### ISSUE THREAD

**Issue by dgcampea** [johman10/flood-for-transmission#160]
Easier navigation and exclusion of directories or files to download.

**Comment by johman10** [comment]
Hi! Thanks for the feature request. But I believe that this request has already been full filled since https://github.com/johman10/flood-for-transmission/issues/122.

You can open it by double clicking on a torrent and opening the files tab in the menu. Hope this helps but do let me know if something doesn't work.

**Comment by dgcampea** [comment]
My bad, turns out I was running an older release.
