### ISSUE TITLE
Have some presets for "Set torrent location"

### ISSUE THREAD

**Issue by cmunk** [johman10/flood-for-transmission#2]
I would like to be able to quickly "move" location to either /videos/movies, /videos/kids or whatever.. 

If I were able to predefine these "frequent" locations it would be great :)

**Comment by johman10** [comment]
This is a great suggestion that I didn't consider yet. It's not a use case I have. However I like it so I will look into this. :)

**Comment by johman10** [comment]
Hi! I just finished this as per https://github.com/johman10/flood-for-transmission/commit/a0bdbd22992b067c7b5bdbe67fe00b5fc174da7e. Thanks for the idea and hope this helps you out.

To use this go into settings => user interface and add a couple of common paths. If you then want to use a common path you can use the magnifier in the "set location" modal to quickly select it.

Hope this helps you! :)

**Comment by realivanjx** [comment]
is there a way to sync or at least export/import common path list? im working on both mobile and pc. im downloading some files weekly and each of those go into different folders.

**Comment by johman10** [comment]
If you know how it works you can extract it from localstorage and put it in the other browser, but since their is no information stored on the server there is no real way for me to sync this information (or any configuration for that matter) between services.

I have seen someone fork this repo and add a hardcoded list to install from instead of the main repo. You can find the example commit here: https://github.com/vasyl-bhd/flood-for-transmission/commit/aef7e0b24d89f705d9287700dafe032da200331e#diff-4b049ea196f984c5efdff949c671572127f627d6a5addaf069f19f5924b1cc8cL8-R13. Downside of this is that you have to make sure to sync your repo with this one for any update. But it wouldn't be impossible to automate that if you want to. ;)

**Comment by realivanjx** [comment]
i think a simple import export button is a good idea since idk how to access localstorage on android chrome

**Comment by johman10** [comment]
@realivanjx that's an interesting suggestion! I can open a new issue for reference and work on it at some point.
