### ISSUE TITLE
Bug: When sorting by ETA in ascending order, infinity is sorted to the top

### ISSUE THREAD

**Issue by leetdavid** [johman10/flood-for-transmission#222]
Bug: When Sorting by ETA in ascending order, infinity is sorted to the top.

I would expect the shortest ETAs to appear at the top, and infinity to be at the bottom of the list.

I imagine this is an issue of infinity being not a number hence it is not being sorted properly.

Example image is shown below:
![image](https://user-images.githubusercontent.com/9511823/127748612-2ef1c49b-f322-431a-b57c-3013d3f37c51.png)

Thanks for making this interface, it was exactly what I was looking for! (and more!)

**Comment by johman10** [comment]
Hi! Good catch, I think that's because Transmission RPC API returns 0 whenever there is no time available. I will have to write some custom logic to take care of that.

I will have a look sometime. Don't know when I will have time but this will probably be a pretty quick fix. :)

Thanks for creating an issue about this! :D

**Comment by johman10** [comment]
@leetdavid this should now be resolved. Transmission return -1 for the ETA when the download speed is 0 or at least super low, so now I changed the sort to overwrite the value with the Maximum possible JS value.

I hope this makes sense. Please test it out and let me know if you have further issues! :)
