### ISSUE TITLE
Bug: Wrong priority when right-clicking on a torrent

### ISSUE THREAD

**Issue by RemiRigal** [johman10/flood-for-transmission#230]
First, thanks for the amazing work, I love this Web UI !

There are two ways to see/modify the priority of a torrent, with a double-click (through the info modal) or a right-click. The info modal works as intended but when I use the right click the priority doesn't seem to be correct. For example if I right-click multiple times on the same torrent without actually changing its priority, the displayed priority changes sometimes.

**Comment by johman10** [comment]
Hi @RemiRigal,

I had a look just now, it seems like it happens when you change the prio in the info modal, but then right click on the list after that. There might be a state there where it doesn't reflect reality until you right click again.

The reason for this is that the info modal and the list represent different datasets that refresh at different times. You see, all information you see in the UI is just requested every second from the server. There is no active open connection. This might mean that the list is slightly outdated when you open the context menu because that dataset wasn't updated yet. They need to be different data sets to minimize the request size for the list. When requesting torrents for the list view the UI will only request those columns that are needed based on the column configuration, however for the info modal it requests a lot more columns for that specific torrent.

An improvement on this might be to double check if I can automatically update the context menu when a new version of the list data comes in. However it will never be instant because of the above mentioned problem. I can look at that.

If you notice this in other scenario please let me know, there might be more to it than what I'm describing here. Also let me know if something is unclear or if you feel that this is totally unreasonable. :)

Either way, thank you for opening an issue! :)

**Comment by RemiRigal** [comment]
Thanks for your answer !

> An improvement on this might be to double check if I can automatically update the context menu when a new version of the list data comes in. However it will never be instant because of the above mentioned problem. I can look at that.

The torrent list is refreshed quite frequently so I think that your proposal is reasonable. Also the PriorityIndicator could be greyed out until the data is refreshed to avoid displaying a potentially wrong value ?

**Comment by johman10** [comment]
That's an interesting suggestion and would be quite a nice experience. However in that case I would have to connect the two data stores somehow and I'm not so sure if I'm such a fan of that pattern. Especially not for something that's, in my eyes, pretty minor. I will consider it while I at least make that small change. Maybe a solution will come to me while working on it. :)

**Comment by RemiRigal** [comment]
I understand your point and I agree with you that `priority` is too minor to break the pattern you have used.

Considering the discussed limitations I think that completely removing the `PriorityIndicator` from the context menu is probably a better solution. It's not an information that needs to be accessed easily and I would rather use the info modal when I know that the displayed priority is right. Let me know what you think :)

**Comment by johman10** [comment]
Hi @RemiRigal!
I had another, more thorough look at this. Personally I quite like being able to right click to change the priority so I would like to keep it in the context menu. For that reason I vouched for my solution. Now, as long as the context menu is open it will update the priority if it changes in another tab or if you're quickly enough to go from torrentDetails into the context menu.

It doesn't mark it as outdated since that would require quite a bit more work for something minor. But it should minimize the cases where the priority is outdated.
