### ISSUE TITLE
Missing: Right Click Menu - Queue

### ISSUE THREAD

**Issue by dannyvfilms** [johman10/flood-for-transmission#337]
First off, hot damn does this look good! I'm using the version paired with `haugene/transmission-openvpn:latest` and was getting some settings back where I usually have then. I noticed that Queue and the submenu options are not available in the right click menu:

<img width="437" alt="Screen Shot 2022-01-28 at 3 41 15 PM" src="https://user-images.githubusercontent.com/44555970/151625474-a3017fff-cb4c-48f6-b2b5-a19df1b1b479.png">
Pictured: https://github.com/transmission-remote-gui/transgui

A little off topic, but Copy Magnet Link also wasn't present. I didn't see a different place to control Queue, so I figured I'd post here. Thanks!

**Comment by johman10** [comment]
> I noticed that Queue and the submenu options are not available in the right click menu

This is correct. I didn't implement any queue prioritization yet. I didn't really decide on how I wanted to do that yet. Idealy I would like to do some kind of drag and drop to prioritize, but perhaps that's too much work and it doesn't work because of the sorting behaviour. This was also discussed on issue [#138](https://github.com/johman10/flood-for-transmission/issues/138#:~:text=enough%20to%20me.-,For%20the%20queue%20position%20I%20don%27t%20think%20that%20should%20live,mind%20for%20a%20while%20but%20nothing%20has%20been%20decided%20yet.,-The%20others%20basically).

I would want to maintain one issue for the queue priotizing, so perhaps we can use the other issue for that. Please subscribe there for future updates.

> A little off topic, but Copy Magnet Link also wasn't present. I didn't see a different place to control Queue, so I figured I'd post here.

Copy magnet link button should be easy to add. I just have to add another item and request the required data from Transmission. I can consider that part of this ticket.

**Comment by johman10** [comment]
Copy Magnet links was now added in the context menu. I will have a look at Queue control next I think since that seems like a basic thing to support, please follow #138 for updates on this topic.

Hope this helps you, let me know if you have more ideas to make Flood for Transmission better!
