### ISSUE TITLE
Add multilple torrents files

### ISSUE THREAD

**Issue by TheFelin** [johman10/flood-for-transmission#4]
Add multiple torrent files and urls

**Comment by johman10** [comment]
Hi! Thanks for the suggestion. I will have a look at this. Will let you know here when it's out! :)

**Comment by johman10** [comment]
This should now be resolved since https://github.com/johman10/flood-for-transmission/commit/15e230a208d320e52871bc10a74f10d3a55ee58b.

Please follow [the update instructions in the readme](https://github.com/johman10/flood-for-transmission#updating) to update and let me know if you experience any problems. :)
