### ISSUE TITLE
Possible to update flood for transmission in a docker container?

### ISSUE THREAD

**Issue by gregmichael** [johman10/flood-for-transmission#408]
I am running specifically - https://github.com/haugene/docker-transmission-openvpn and flood for transmissionwas pre-packaged with that fork of transmission.

**Comment by johman10** [comment]
You can probably run a shell within the container with `docker exec -it [container-name] /bin/bash` and execute this line:
https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile#L9.

I'm not 100% sure how this will behave upon container restarts thoughs. I would recommend that you read more about docker, if upgrades to the image are important to you you should be talking with the creator of the docker image you're running.

Closing this since this is not really an issue for Flood for Transmission.
