### ISSUE TITLE
Unable to set labels

### ISSUE THREAD

**Issue by gapple** [johman10/flood-for-transmission#452]
When trying to set a label, the UI locks up with an error in the console 
- in Firefox: `Uncaught (in promise) TypeError: t.labels is undefined`
- in Chrome: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')`

**Comment by johman10** [comment]
Are you using Transmission 3.00? Labels will only work when you run the latest version of Transmission since it was added in 3.00.

If you running [haugene/docker-transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn) you will be running and older version of Transmission.

Labels should be the only thing that doesn't work with an older version.

**Comment by gapple** [comment]
That would make sense; thanks for the quick response.

Not sure if it's possible / practical to hide the labels functionality if not available?
