### ISSUE TITLE
Settings not stored?

### ISSUE THREAD

**Issue by luchaze** [johman10/flood-for-transmission#480]
I know the settings for transmission are stored in the settings.json file but the additional settings new in this webui don't seem to persist on different computers / browsers, are they stored locally? 

if so, can you make an additional settings file so we can store the settings server side so they maintain regardless of where the site i accessed from?

**Comment by johman10** [comment]
Hi,
Settings for Transmission are stored on the file system in the settings.json file that you're referring to. However user interface settings are stored within the However because those are not relevant for Transmission and there is no backend service to save it at since it's just HTML and JS. This means that switching computer/browser will force you to reconfigure the UI, not many ways around it.

I think this will partly be solved as part of https://github.com/johman10/flood-for-transmission/issues/434. Where, hopefully, you can create your own config file, store in cloud storage and reapply for every browser you use without issues.

**Comment by luchaze** [comment]
Ok, well wat i means was just creating a simple config file for the UI settings and have JS pull default data from there. would seem like easy addition and very usefull i think.

But anyways, no rush for me anymore, i ended up editing the main.js myself last night to have darkmode always enabled and added some default storage paths. the rest i wanted i did though css. 

But thanks for the great UI, much better than the default transmission UI!

**Comment by johman10** [comment]
> Ok, well wat i means was just creating a simple config file for the UI settings and have JS pull default data from there. would seem like easy addition and very usefull i think.

This is part of the consideration for the export feature request. To have a file which contains default config that can be edited manually and served via the browser as a JS file. So once I get around to that you might just find this feature!

I'm glad you like it! I'm always happy to hear that people like the things I build in my free time. :)
