### ISSUE TITLE
Show ip of host

### ISSUE THREAD

**Issue by trexxeon** [johman10/flood-for-transmission#533]
Would it be possible to get the ip to show in the UI like deluge does?

**Comment by johman10** [comment]
I looked at the API docs and I can't find any way to expose this information. The best way would be to query the [a DNS provider like Cloudflare](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/) and ask for this information. However, that's quite a bit of effort to go through because there will be lots of edge cases to handle such as:
- What if you access directly via IP
- Merging all of it with ports
- Integrating with a different API and all the error cases

Because of this I rather not go this route. But if you let me know about your usecase I can reconsider it.
