### ISSUE TITLE
Improvements to Readability

### ISSUE THREAD

**Issue by lorenzolewis** [johman10/flood-for-transmission#54]
Overall I love this theme! However I feel the content's readability in the sidebar could be improved. Increasing the overall font size by a few points and changing the text colors to be brighter would help a ton! If you want to keep the focus on the list of torrents and not distract via the sidebar, then maybe only increase the brightness when the mouse is hovered over the sidebar. Would be more than happy to help with colors, etc. if you'd like! 
![49A33353-1A1F-4F20-A644-33E294EF1183](https://user-images.githubusercontent.com/15347255/108606120-debd8280-737d-11eb-8f5f-830f4791e3db.png)

**Comment by johman10** [comment]
Hi! Thanks for the input! I'm working on a dark mode as per https://github.com/johman10/flood-for-transmission/issues/6. I will consider this to be a next step after that. Some colors will change during my work there already, however I don't think entirely resolves what you're talking about here.

Hang tight and I will have a look at this eventually! :)

Will let you know if I need help/input here.

**Comment by johman10** [comment]
@gigawatts documented some changes he did with some theme'ing engine here: https://github.com/jesec/flood/discussions/213.

I don't have any intention to implement a theme'ing thing into this projects, however the contrast should be looked at.

**Comment by gigawatts** [comment]
> @gigawatts documented some changes he did with some theme'ing engine here: [jesec/flood#213](https://github.com/jesec/flood/discussions/213).
> 
> I don't have any intention to implement a theme'ing thing into this projects, however the contrast should be looked at.

Just a small follow up, I made a few more small tweaks to my tamper monkey userscript and published it to a Github Gist, mostly so I can sync updates between my own PCs, but also so I can share this with anyone else that wants to use it too!

https://gist.github.com/gigawatts/eee083fe09a9d09a726199322c62a99e/

**Comment by johman10** [comment]
As pointed out above. I think this should be resolved with https://github.com/johman10/flood-for-transmission/commit/b64214ebec3a8550115995a6340924fb635519fb.

Please let me know if you have any specific input on the color usage (also check out dark mode, it might give you some more contrast in the torrent list at least.

To check it out follow the [update instructions in the README](https://github.com/johman10/flood-for-transmission#updating).

Hope this helps to make Flood for Transmission better. ;)

**Comment by gigawatts** [comment]
I like the new use of variables, that makes creating further tweaks in TamperMonkey MUCH easier! 

The contrast in the update is a tiny bit better, but I still believe it could use more contrast between the text color and the side panel background color.

I like the dark mode toggle, and I'll probably mostly use dark mode enabled, but for "light mode", there is now too much contrast between the left side panel (which doesn't change with the toggle) and the right side panel. Perhaps a ".light-mode {}" section could be added to your colors.css (along with appropriate class tags on the main/divs) so that the left side panel can get its own set of "light mode" colors to jive better with the right side panel.

**Comment by johman10** [comment]
@gigawatts thanks for the input! :)

> but for "light mode", there is now too much contrast between the left side panel (which doesn't change with the toggle) and the right side panel.

Personally I actually enjoy this contrast, it separates the sections nice and clearly, while putting the focus onto the right part. Even though you're in "light mode" doesn't mean that all of the content has to be on a light background in my believe. When it comes to darkmode it's a little different since there the user chooses specifically that they only want a dark background, which is what the current version of darkmode already resolves.

If you believe the side panel should be light, feel free to use TamperMonkey for it as you do already. The color variables should keep the CSS working for a longer time at least. :)
