### ISSUE TITLE
Destination must be an absolute path on windows

### ISSUE THREAD

**Issue by xiaobai-sci** [johman10/flood-for-transmission#551]
![image](https://github.com/johman10/flood-for-transmission/assets/40563848/75820bfa-c848-4354-8d67-c43eb7373ecc)
I saw that you mentioned the problem has been resolved earlier. However, I downloaded the latest version, and the error still persists.

**Comment by iRaschen** [comment]
check the beginning of the path for a space "[space]D:\Jellyfin\TV"

**Comment by johman10** [comment]
It's not a space actually, it's just the padding of the field you're seeing.

It seems like the validation is a bit too strict an only allowing paths that start with a `/` because Linux. The validation is specified here: https://github.com/johman10/flood-for-transmission/blob/master/src/components/Modal/Location/Location.svelte#L62

I seem to have changed it in one place but not all of them: https://github.com/johman10/flood-for-transmission/blob/master/src/components/Modal/Add/Add.svelte#L150.

The other place the validation is used but wrong is here: https://github.com/johman10/flood-for-transmission/blob/master/src/components/Modal/Settings/UserInterface.svelte#L99.

I think this pattern regex should live more centrally and be loaded into the componets where it's needed instead of hardcoded. I can create a PR for this now.
